"""Regression tests for status/nav synchronization (see `synth.report`).

The published status page and the site navigation are claims about what the
repository holds. They must be regenerated by the work that invalidates them,
they must be reproducible from committed state alone so CI can detect drift,
and they must distinguish a valid cached note from a malformed one. No model
calls, no network. Run with `uv run pytest`.
"""
from __future__ import annotations

import json
from types import SimpleNamespace

import pytest

from self_assessment_wiki.synth import build, compose, extract, nav, report, store
from self_assessment_wiki.synth.chunk import Chunk

NOTE = {"relevance": "core", "summary": "A person must deliver a return.",
        "topics": [], "obligations": [], "deadlines": [], "amounts": [],
        "penalties": [], "definitions": [], "cross_references": [], "caveats": []}

SPECS = [
    {"id": "who-must-file", "title": "Who must file", "section": "The lifecycle",
     "output": "docs/lifecycle/who-must-file.md", "brief": "Who is brought in.",
     "authorities": ["tma-1970"], "select": {"relevance": ["core"]}},
    {"id": "deadlines", "title": "Deadlines", "section": "The lifecycle",
     "output": "docs/lifecycle/deadlines.md", "brief": "When things are due.",
     "authorities": ["tma-1970"], "select": {"relevance": ["core"]}},
    {"id": "penalties", "title": "Penalties", "section": "The lifecycle",
     "output": "docs/lifecycle/penalties.md", "brief": "What it costs.",
     "authorities": ["tma-1970"], "select": {"relevance": ["core"]}},
]


def chunks(n: int) -> list[Chunk]:
    return [Chunk(doc="legislation/tma-1970.md", index=i, heading_path=[f"s.{i}"],
                  text=f"body {i}", hash=f"hash{i}") for i in range(n)]


def entry(chunk: Chunk, note: dict | None = None) -> dict:
    return {"index": chunk.index, "heading": chunk.heading,
            "prompt_hash": extract.PROMPT_HASH, "model": "fake:model",
            "note": dict(NOTE) if note is None else note}


@pytest.fixture
def repo(monkeypatch, tmp_path):
    """A whole small pipeline on disk: one document, three pages, all fresh.

    Everything the report reads is redirected here, so the tests can move one
    input at a time and watch the published claim follow it.
    """
    docs = tmp_path / "docs"
    (docs / "lifecycle").mkdir(parents=True)
    (docs / "meta").mkdir()
    (docs / "index.md").write_text("# Home\n")

    cached = chunks(3)
    plan = extract.Plan(doc="legislation/tma-1970.md", meta={}, chunks=cached,
                        todo=[], orphans=0)
    extracts = {"legislation/tma-1970.md": {
        "doc": "legislation/tma-1970.md", "source_id": "tma-1970",
        "chunks": {c.hash: entry(c) for c in cached}}}

    manifest = {}
    for spec in SPECS:
        (tmp_path / spec["output"]).write_text(f"# {spec['title']}\n")
        notes = compose.select(spec, extracts)
        manifest[spec["id"]] = {
            "generated_by": "fake:model", "generated_on": "2026-09-01",
            "input_hash": compose.input_hash(spec, notes, "model"),
            "note_count": len(notes), "output": spec["output"]}

    monkeypatch.setattr(report, "OUTPUT", docs / "meta" / "wiki-status.md")
    monkeypatch.setattr(nav, "DOCS_DIR", docs)
    monkeypatch.setattr(nav, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(report, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(compose, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(compose, "load_pages", lambda: list(SPECS))
    monkeypatch.setattr(compose, "load_manifest", lambda: manifest)
    monkeypatch.setattr(extract, "plan", lambda only=None: [plan])
    monkeypatch.setattr(store, "load_all", lambda: extracts)
    monkeypatch.setattr(report.pipeline_fetch, "load_sources", lambda: [])
    monkeypatch.setattr(report.manifest_store, "load",
                        lambda: {"tma-1970": {"last_checked": "2026-09-02"}})

    return SimpleNamespace(root=tmp_path, docs=docs, plan=plan,
                           extracts=extracts, manifest=manifest)


def status_text(repo) -> str:
    return report.render()


# --- the report is a function of committed state, not of the clock ----------

def test_two_runs_over_the_same_tree_produce_the_same_bytes(repo):
    assert report.render() == report.render()
    assert report.files() == report.files()


def test_a_complete_pipeline_is_reported_as_one(repo):
    text = status_text(repo)
    assert "complete end-to-end run" in text
    assert "No complete end-to-end run" not in text
    # Dated from the artifacts themselves, not from today.
    assert "finished 2026-09-01" in text
    assert "Corpus last checked upstream: 2026-09-02" in text



def test_status_contains_the_source_to_page_authority_matrix(repo):
    text = status_text(repo)
    assert "## Page authority coverage" in text
    assert "| Page | Authorities | Missing |" in text
    assert text.count("| 1/1 | - |") == len(SPECS)

def test_an_unextracted_chunk_withdraws_the_completeness_claim(repo):
    repo.plan.todo = repo.plan.chunks[:1]
    text = status_text(repo)
    assert "**No complete end-to-end run is represented" in text
    assert "1 chunk(s) have never been extracted" in text


def test_a_stale_page_withdraws_the_completeness_claim(repo):
    repo.manifest["penalties"]["input_hash"] = "0000000000000000"
    text = status_text(repo)
    assert "**No complete end-to-end run is represented" in text
    assert "1 page(s) are stale or missing: `penalties`" in text
    assert "| stale |" in text


def test_a_deleted_page_file_is_reported_as_missing(repo):
    (repo.docs / "lifecycle" / "penalties.md").unlink()
    assert "| missing |" in status_text(repo)


def test_a_never_composed_page_is_reported_as_such(repo):
    del repo.manifest["penalties"]
    text = status_text(repo)
    assert "| not yet generated |" in text
    assert "1 planned page(s) have never been composed: `penalties`" in text


# --- valid cache entries are distinguished from malformed ones -------------

def test_a_malformed_note_is_counted_as_invalid_not_as_coverage(repo):
    bad = repo.plan.chunks[0]
    repo.extracts["legislation/tma-1970.md"]["chunks"][bad.hash] = \
        entry(bad, {"relevance": "core"})  # every other required key missing
    repo.plan.invalid = [bad]
    repo.plan.todo = [bad]

    text = status_text(repo)
    assert "2 of 3 corpus chunks extracted" in text
    assert "1 cached note(s) do not, and are queued for re-extraction" in text
    assert "### Notes that fail the extract schema" in text
    assert "| `corpus/legislation/tma-1970.md` | 1 |" in text
    assert "| invalid | 1 |" in text
    assert "1 cached note(s) fail the extract schema" in text


def test_a_healthy_cache_reports_no_invalid_section(repo):
    text = status_text(repo)
    assert "### Notes that fail the extract schema" not in text
    assert "| invalid |" not in text


def test_a_missing_corpus_artifact_is_named(repo, monkeypatch):
    monkeypatch.setattr(report.reconcile, "audit",
                        lambda sources: type("A", (), {"failed": [
                            {"unit": "tma-1970", "error": "no file at corpus/tma-1970.md"}]})())
    text = status_text(repo)
    assert "- `tma-1970`: no file at corpus/tma-1970.md" in text
    assert "1 fetched source(s) have no artifact in `corpus/`" in text


# --- the nav follows pages.yml --------------------------------------------

def test_nav_lists_pages_in_the_order_of_the_page_plan(repo):
    written = nav.render()[repo.docs / "lifecycle" / ".pages"]
    assert written.splitlines()[2:] == [
        "nav:", "  - who-must-file.md", "  - deadlines.md",
        "  - penalties.md", "  - ...",
    ]


def test_a_page_that_was_never_composed_is_left_out_of_the_nav(repo):
    """awesome-pages warns on an entry it can't resolve, and --strict fails."""
    (repo.docs / "lifecycle" / "deadlines.md").unlink()
    written = nav.render()[repo.docs / "lifecycle" / ".pages"]
    assert "deadlines.md" not in written
    assert "  - who-must-file.md" in written


def test_the_real_page_plan_orders_the_committed_lifecycle_pages(monkeypatch):
    """No fixtures: the nav this repository actually publishes."""
    from self_assessment_wiki.synth.config import DOCS_DIR
    listed = [line.strip("- ").strip()
              for line in nav.render()[DOCS_DIR / "lifecycle" / ".pages"].splitlines()
              if line.startswith("  - ") and line.strip() != "- ..."]
    planned = [p["output"].split("/")[-1] for p in compose.load_pages()
               if p["output"].startswith("docs/lifecycle/")
               and (DOCS_DIR.parent / p["output"]).exists()]
    assert listed == planned and len(listed) >= 3


# --- drift detection -------------------------------------------------------

def test_check_passes_once_the_generated_files_are_written(repo):
    report.write_all()
    assert report.drift() == []
    assert report.main(["--check"]) == 0


def test_one_pass_over_a_clean_tree_converges(repo):
    """`uv run report` then `--check` in CI: the first run must be enough.

    The nav depends on which pages exist, and the status page is one of them,
    so a render that read the tree naively would only settle on the second
    run - and CI would fail on a freshly generated tree.
    """
    first = report.write_all()
    assert report.drift() == []
    assert report.write_all() == first


def test_check_fails_when_nothing_has_been_generated_yet(repo, monkeypatch):
    monkeypatch.setattr(report.compose, "load_pages", lambda: list(SPECS))
    assert report.OUTPUT.exists() is False
    assert report.main(["--check"]) == 1


def test_check_fails_when_a_committed_file_no_longer_matches(repo):
    report.write_all()
    report.OUTPUT.write_text("# Wiki status\n\nEverything is fine.\n")
    assert report.drift() == [report.OUTPUT]
    assert report.main(["--check"]) == 1
    assert report.main([]) == 0 and report.drift() == []


def test_check_writes_nothing(repo):
    report.write_all()
    before = {p: p.read_text() for p in report.files()}
    repo.manifest["penalties"]["input_hash"] = "0000000000000000"
    assert report.main(["--check"]) == 1
    assert {p: p.read_text() for p in before} == before


# --- the CLI cannot leave the two behind -----------------------------------

@pytest.fixture
def cli(monkeypatch, tmp_path):
    """`build.main` with the model stages stubbed and the resync recorded."""
    resyncs: list[int] = []
    monkeypatch.setattr(build, "RUN_REPORT_PATH", tmp_path / "last_run.json")
    monkeypatch.setattr(build, "get_backend", lambda *a, **k: None)
    monkeypatch.setattr(build.report, "write_all",
                        lambda: resyncs.append(1) or [])
    return resyncs


def staged(stage: str, *, succeeded: int, failed: int):
    from self_assessment_wiki import runlog

    def run(*args, **kwargs):
        rep = runlog.StageReport(stage=stage, unit="unit")
        for i in range(succeeded):
            rep.succeed(f"{stage}-ok-{i}")
        for i in range(failed):
            rep.fail(f"{stage}-bad-{i}", "model refused")
        return rep
    return run


def test_a_successful_extract_regenerates_the_status_and_nav(cli, monkeypatch):
    monkeypatch.setattr(extract, "run", staged("extract", succeeded=2, failed=0))
    assert build.main([], command="extract") == 0
    assert cli == [1]


def test_a_successful_compose_regenerates_the_status_and_nav(cli, monkeypatch):
    monkeypatch.setattr(compose, "run", staged("compose", succeeded=2, failed=0))
    assert build.main([], command="compose") == 0
    assert cli == [1]


def test_a_partial_run_still_resyncs_before_failing(cli, monkeypatch):
    """It wrote pages; the status page has to describe the tree it left."""
    monkeypatch.setattr(compose, "run", staged("compose", succeeded=1, failed=1))
    assert build.main([], command="compose") == 1
    assert cli == [1]


def test_a_run_that_wrote_nothing_leaves_the_generated_files_alone(cli, monkeypatch):
    monkeypatch.setattr(compose, "run", staged("compose", succeeded=0, failed=1))
    assert build.main([], command="compose") == 1
    assert cli == []


def test_a_dry_run_never_resyncs(cli, monkeypatch):
    monkeypatch.setattr(compose, "plan", lambda *a, **k: [])
    assert build.main(["--dry-run"], command="compose") == 0
    assert cli == []


def test_synth_all_resyncs_once_both_stages_have_run(cli, monkeypatch):
    monkeypatch.setattr(extract, "run", staged("extract", succeeded=1, failed=0))
    monkeypatch.setattr(compose, "run", staged("compose", succeeded=1, failed=0))
    assert build.main([], command="all") == 0
    assert cli == [1]
    stages = json.loads((build.RUN_REPORT_PATH).read_text())["stages"]
    assert [s["stage"] for s in stages] == ["extract", "compose"]
