"""Schema and path-containment checks for `sources.yml` and `pages.yml`.

Both files were trusted. A typo in `type` surfaced as "no fetcher for
type=..." after the rest of the run had already spent network calls; a
misspelled `relevance` tier silently selected nothing and composed a page
from no notes; an `output` of `../../etc/motd` or `/tmp/x` would have been
written wherever it pointed, because every writer just did
`Path(entry["output"]).write_text(...)`.

So configuration is validated up front, before any network, model or
file-write work: `load_sources()` and `load_pages()` raise `ConfigError`
listing every problem at once, and every command reads its config through
them.

The rules that are not just "this key must be a string":

- `output` (and `items_dir`, and a page's `select.docs` prefixes) must be a
  relative POSIX path under the root that kind of artifact belongs to -
  `corpus/` for fetched material, `docs/` for composed pages. Absolute paths
  and `..` traversal are rejected.
- A page may not write to a hand-maintained or separately generated file; the
  compose stage would silently overwrite it.
- Two sources may share one `output` only as explicit `web_page` sections,
  each owning a distinct `<!-- section:ID -->` block (see
  `pipeline/fetchers/web_page.py`). Anything else sharing an output is two
  writers racing for one file.
- A GOV.UK `url` is a Content API path (`/guidance/...`), everything else is
  an absolute URL. Getting this backwards fails deep inside a fetcher.
"""
from __future__ import annotations

import re
from pathlib import PurePosixPath

import yaml

ID_RE = re.compile(r"^[a-z0-9][a-z0-9._-]*$")
CATEGORY_RE = re.compile(r"^[a-z0-9]+(?:[-][a-z0-9]+)*(?:\.[a-z0-9]+(?:[-][a-z0-9]+)*)*$")

# Source `type` -> the shape of its `url`. "path" types are GOV.UK Content API
# paths resolved against https://www.gov.uk/api/content; "url" types are
# fetched as given.
SOURCE_TYPES = {
    "legislation": "url",
    "govuk_content": "path",
    "govuk_content_collection": "path",
    "govuk_content_manual": "path",
    "caselaw_feed": "url",
    "web_page": "url",
}
STATUSES = ("fetch", "registered")
HTML_ATTACHMENT_MODES = ("latest", "all", "none")

SOURCE_REQUIRED = ("id", "category", "type", "title", "url", "status")
# Allowed on any source: `output` is required for `status: fetch` (checked
# below), `note` is documentation for a human reading the registry.
SOURCE_OPTIONAL = ("output", "note")
# Keys only the named fetcher reads. Setting one on another type is a silent
# no-op, which is how `max_items` ends up on a manual and caps nothing.
SOURCE_TYPE_KEYS: dict[str, tuple[str, ...]] = {
    "legislation": (),
    "govuk_content": ("html_attachments",),
    "govuk_content_collection": ("expand_items", "items_dir", "html_attachments"),
    "govuk_content_manual": ("max_sections",),
    "caselaw_feed": ("max_items",),
    "web_page": ("section",),
}

PAGE_REQUIRED = ("id", "title", "section", "output", "brief", "authorities")
PAGE_OPTIONAL = ("select",)
SELECT_KEYS = ("docs", "relevance", "match", "max_notes")
RELEVANCE_TIERS = ("core", "related", "none")

CORPUS_ROOT = "corpus"
DOCS_ROOT = "docs"

# docs/ files no page may claim: hand-written, or generated by something other
# than compose (see AGENTS.md "Do not hand-edit").
PROTECTED_OUTPUTS = frozenset({
    "docs/index.md",
    "docs/external-explainers.md",
    "docs/reference-implementation/data-model-notes.md",
    "docs/meta/refresh-process.md",
    "docs/meta/sources.md",
    "docs/meta/wiki-status.md",
})


class ConfigError(Exception):
    """Raised before any work starts, listing every configuration problem."""

    def __init__(self, label: str, errors: list[str]):
        self.label = label
        self.errors = errors
        super().__init__(f"{label}: {len(errors)} problem(s)\n"
                         + "\n".join(f"  - {e}" for e in errors))


def _is_str(value: object) -> bool:
    return isinstance(value, str) and bool(value.strip())


def _check_keys(errors: list[str], where: str, entry: dict,
                required: tuple[str, ...], allowed: tuple[str, ...]) -> None:
    for key in required:
        if key not in entry:
            errors.append(f"{where}: missing key {key!r}")
    for key in sorted(set(entry) - set(required) - set(allowed)):
        errors.append(f"{where}: unexpected key {key!r}")


def path_problem(value: object, root: str, *, allow_file: bool = True) -> str | None:
    """Why `value` is not a safe repo-relative path under `root`, or None.

    Rejects anything that could write outside the root it belongs to: an
    absolute path, a Windows path, a `~` expansion, any `..` segment, and any
    path whose first segment is not `root`.
    """
    if not _is_str(value):
        return "must be a non-empty string path"
    if "\\" in value:
        return f"is not a POSIX path: {value!r}"
    if value.startswith("~"):
        return f"is a home-relative path: {value!r}"
    path = PurePosixPath(value)
    if path.is_absolute():
        return f"is an absolute path: {value!r}"
    # On the raw segments, not the normalised ones: PurePosixPath folds `.`
    # and `//` away silently, and either is a sign the path was assembled by
    # string concatenation rather than written out.
    raw = value.split("/")
    if ".." in raw:
        return f"escapes the repository with `..`: {value!r}"
    if "." in raw or "" in raw[:-1]:
        return f"has an empty or `.` path segment: {value!r}"
    parts = path.parts
    if not parts or parts[0] != root:
        return f"must live under {root}/: {value!r}"
    if len(parts) < 2:
        return f"is {root}/ itself, not a path inside it: {value!r}"
    if allow_file and path.suffix != ".md":
        return f"must be a .md file: {value!r}"
    return None


def _check_positive_int(errors: list[str], where: str, entry: dict, key: str) -> None:
    if key not in entry:
        return
    value = entry[key]
    # bool is an int in Python; a `max_items: true` is a mistake, not a cap.
    if isinstance(value, bool) or not isinstance(value, int) or value < 1:
        errors.append(f"{where}: {key} must be a positive integer, got {value!r}")


def validate_sources(sources: object) -> list[str]:
    """Every reason `sources` is not a usable source registry."""
    if not isinstance(sources, list) or not sources:
        return [f"expected a non-empty list of source entries, got "
                f"{type(sources).__name__}"]

    errors: list[str] = []
    seen_ids: set[str] = set()
    # output path -> [(id, section or None)], to judge intentional sharing.
    outputs: dict[str, list[tuple[str, str | None]]] = {}

    for i, entry in enumerate(sources):
        where = f"[{i}]"
        if not isinstance(entry, dict):
            errors.append(f"{where}: expected a mapping, got {type(entry).__name__}")
            continue
        if _is_str(entry.get("id")):
            where = f"[{i}] {entry['id']}"

        stype = entry.get("type")
        allowed = SOURCE_OPTIONAL + SOURCE_TYPE_KEYS.get(stype, ())
        _check_keys(errors, where, entry, SOURCE_REQUIRED, allowed)

        sid = entry.get("id")
        if not _is_str(sid) or not ID_RE.match(sid):
            errors.append(f"{where}: id must be a lowercase slug, got {sid!r}")
        elif sid in seen_ids:
            errors.append(f"{where}: duplicate source id {sid!r}")
        else:
            seen_ids.add(sid)

        if stype not in SOURCE_TYPES:
            errors.append(f"{where}: type must be one of "
                          f"{', '.join(sorted(SOURCE_TYPES))}, got {stype!r}")

        status = entry.get("status")
        if status not in STATUSES:
            errors.append(f"{where}: status must be one of {', '.join(STATUSES)}, "
                          f"got {status!r}")

        for key in ("title", "url"):
            if key in entry and not _is_str(entry[key]):
                errors.append(f"{where}: {key} must be a non-empty string, "
                              f"got {entry[key]!r}")

        category = entry.get("category")
        if "category" in entry and (not _is_str(category) or not CATEGORY_RE.match(category)):
            errors.append(f"{where}: category must be a dotted lowercase path, "
                          f"got {category!r}")

        url, url_form = entry.get("url"), SOURCE_TYPES.get(stype)
        if _is_str(url) and url_form == "url" and not re.match(r"^https?://", url):
            errors.append(f"{where}: {stype} url must be absolute, got {url!r}")
        if _is_str(url) and url_form == "path" and not url.startswith("/"):
            errors.append(f"{where}: {stype} url must be a GOV.UK Content API path "
                          f"starting with `/`, got {url!r}")

        output = entry.get("output")
        if status == "fetch" and output is None:
            errors.append(f"{where}: status: fetch needs an output path")
        elif output is not None:
            issue = path_problem(output, CORPUS_ROOT)
            if issue:
                errors.append(f"{where}: output {issue}")
            elif _is_str(sid):
                section = entry.get("section") if stype == "web_page" else None
                outputs.setdefault(output, []).append((sid, section or sid))

        if "section" in entry:
            section = entry["section"]
            if not _is_str(section) or not ID_RE.match(section):
                errors.append(f"{where}: section must be a lowercase slug, "
                              f"got {section!r}")

        if "html_attachments" in entry and entry["html_attachments"] not in HTML_ATTACHMENT_MODES:
            errors.append(f"{where}: html_attachments must be one of "
                          f"{', '.join(HTML_ATTACHMENT_MODES)}, "
                          f"got {entry['html_attachments']!r}")

        _check_positive_int(errors, where, entry, "max_items")
        _check_positive_int(errors, where, entry, "max_sections")

        if "expand_items" in entry and not isinstance(entry["expand_items"], bool):
            errors.append(f"{where}: expand_items must be true or false, "
                          f"got {entry['expand_items']!r}")
        if entry.get("expand_items"):
            items_dir = entry.get("items_dir")
            if items_dir is None:
                errors.append(f"{where}: expand_items needs items_dir "
                              f"(where the member pages are written)")
            else:
                issue = path_problem(items_dir, CORPUS_ROOT, allow_file=False)
                if issue:
                    errors.append(f"{where}: items_dir {issue}")
                elif _is_str(output) and items_dir != PurePosixPath(output).parent.as_posix():
                    errors.append(
                        f"{where}: items_dir must be the directory holding output "
                        f"({PurePosixPath(output).parent.as_posix()!r}), got {items_dir!r}")

    errors += _shared_output_errors(sources, outputs)
    return errors


def _shared_output_errors(
        sources: list, outputs: dict[str, list[tuple[str, str | None]]]) -> list[str]:
    """Outputs claimed by more than one source, unless shared on purpose."""
    by_id = {s["id"]: s for s in sources
             if isinstance(s, dict) and _is_str(s.get("id"))}
    errors: list[str] = []
    for output, claimants in sorted(outputs.items()):
        if len(claimants) < 2:
            continue
        ids = [sid for sid, _ in claimants]
        not_shareable = [sid for sid in ids if by_id[sid].get("type") != "web_page"]
        if not_shareable:
            errors.append(
                f"output {output!r} is claimed by {', '.join(ids)}; only web_page "
                f"sources may share an output, via distinct `section:` blocks "
                f"({', '.join(not_shareable)} cannot)")
            continue
        sections = [section for _, section in claimants]
        clashing = sorted({s for s in sections if sections.count(s) > 1})
        if clashing:
            errors.append(f"output {output!r}: section(s) {', '.join(clashing)} "
                          f"claimed by more than one source")
    return errors


def validate_pages(pages: object) -> list[str]:
    """Every reason `pages` is not a usable page plan."""
    if not isinstance(pages, list) or not pages:
        return [f"expected a non-empty list of page entries, got {type(pages).__name__}"]

    errors: list[str] = []
    seen_ids: set[str] = set()
    seen_outputs: dict[str, str] = {}

    for i, entry in enumerate(pages):
        where = f"[{i}]"
        if not isinstance(entry, dict):
            errors.append(f"{where}: expected a mapping, got {type(entry).__name__}")
            continue
        if _is_str(entry.get("id")):
            where = f"[{i}] {entry['id']}"

        _check_keys(errors, where, entry, PAGE_REQUIRED, PAGE_OPTIONAL)

        pid = entry.get("id")
        if not _is_str(pid) or not ID_RE.match(pid):
            errors.append(f"{where}: id must be a lowercase slug, got {pid!r}")
        elif pid in seen_ids:
            errors.append(f"{where}: duplicate page id {pid!r}")
        else:
            seen_ids.add(pid)

        for key in ("title", "section", "brief"):
            if key in entry and not _is_str(entry[key]):
                errors.append(f"{where}: {key} must be a non-empty string, "
                              f"got {entry[key]!r}")

        authorities = entry.get("authorities")
        if "authorities" in entry and (not isinstance(authorities, list) or not authorities):
            errors.append(f"{where}: authorities must be a non-empty list of source ids")
        elif isinstance(authorities, list):
            seen_authorities: set[str] = set()
            for authority in authorities:
                if not _is_str(authority) or not ID_RE.match(authority):
                    errors.append(f"{where}: authorities entries must be lowercase source "
                                  f"id slugs, got {authority!r}")
                elif authority in seen_authorities:
                    errors.append(f"{where}: duplicate authority {authority!r}")
                else:
                    seen_authorities.add(authority)

        output = entry.get("output")
        if output is not None:
            issue = path_problem(output, DOCS_ROOT)
            if issue:
                errors.append(f"{where}: output {issue}")
            elif output in PROTECTED_OUTPUTS:
                errors.append(f"{where}: output {output} is maintained outside the "
                              f"compose stage; composing it would overwrite it")
            elif output in seen_outputs:
                errors.append(f"{where}: output {output} is already written by "
                              f"{seen_outputs[output]}")
            else:
                seen_outputs[output] = pid if _is_str(pid) else where

        if "select" in entry:
            errors += _select_errors(where, entry["select"])

    return errors


def _select_errors(where: str, select: object) -> list[str]:
    if not isinstance(select, dict):
        return [f"{where}: select must be a mapping, got {type(select).__name__}"]

    errors: list[str] = []
    _check_keys(errors, f"{where} select", select, (), SELECT_KEYS)

    for prefix in _as_list(errors, where, select, "docs"):
        if not _is_str(prefix):
            errors.append(f"{where}: select.docs entries must be non-empty strings, "
                          f"got {prefix!r}")
            continue
        if prefix.startswith(("/", "corpus/", "docs/")) or ".." in PurePosixPath(prefix).parts:
            errors.append(f"{where}: select.docs entries are corpus-relative path "
                          f"prefixes (no leading `/` or `corpus/`), got {prefix!r}")

    for tier in _as_list(errors, where, select, "relevance"):
        if tier not in RELEVANCE_TIERS:
            errors.append(f"{where}: select.relevance must be drawn from "
                          f"{', '.join(RELEVANCE_TIERS)}, got {tier!r}")

    for pattern in _as_list(errors, where, select, "match"):
        if not _is_str(pattern):
            errors.append(f"{where}: select.match entries must be non-empty regexes, "
                          f"got {pattern!r}")
            continue
        try:
            re.compile(pattern)
        except re.error as exc:
            errors.append(f"{where}: select.match {pattern!r} does not compile: {exc}")

    _check_positive_int(errors, f"{where} select", select, "max_notes")
    return errors


def _as_list(errors: list[str], where: str, select: dict, key: str) -> list:
    """`select[key]` as a list, recording an error if it is not one."""
    if key not in select:
        return []
    value = select[key]
    if not isinstance(value, list):
        errors.append(f"{where}: select.{key} must be a list, got "
                      f"{type(value).__name__}")
        return []
    return value


def _load(path, validator, label: str):
    data = yaml.safe_load(path.read_text())
    errors = validator(data)
    if errors:
        raise ConfigError(label, errors)
    return data


def validate_authority_references(pages: list[dict], sources: list[dict]) -> list[str]:
    """Authorities in the page matrix must name a registered source."""
    known = {source.get("id") for source in sources if isinstance(source, dict)}
    errors = []
    for page in pages:
        if not isinstance(page, dict):
            continue
        for source_id in page.get("authorities") or []:
            if source_id not in known:
                errors.append(f"{page.get('id', '<unknown>')}: authority {source_id!r} "
                              "is not present in sources.yml")
    return errors


def load_sources(path) -> list[dict]:
    """`sources.yml`, validated. Raises ConfigError if it is not usable."""
    return _load(path, validate_sources, f"{path.name} (source registry)")


def load_pages(path) -> list[dict]:
    """`pages.yml`, validated. Raises ConfigError if it is not usable."""
    return _load(path, validate_pages, f"{path.name} (page plan)")
