"""Write docs/meta/wiki-status.md - a deterministic, no-model-calls report on
how much of the corpus has been extracted and how fresh each wiki page is -
and the .pages nav files that order the site.

Run at the end of `uv run extract` / `uv run compose`, or on its own:

    uv run report
"""
from __future__ import annotations

from datetime import date

from ..pipeline import fetch as pipeline_fetch
from ..pipeline import reconcile
from . import compose, extract, nav, schema, store
from .config import DOCS_DIR

OUTPUT = DOCS_DIR / "meta" / "wiki-status.md"


def render() -> str:
    plans = extract.plan()
    extracts = store.load_all()
    manifest = compose.load_manifest()
    specs = compose.load_pages()

    total = sum(len(p.chunks) for p in plans)
    done = sum(len(p.chunks) - len(p.todo) for p in plans)
    invalid = sum(len(p.invalid) for p in plans)
    relevance: dict[str, int] = {}
    for data in extracts.values():
        for entry in data.get("chunks", {}).values():
            # An unusable note is counted as invalid, not as a relevance
            # judgement it never made.
            key = ("invalid" if not schema.entry_is_valid(entry)
                   else (entry.get("note") or {}).get("relevance", "unknown"))
            relevance[key] = relevance.get(key, 0) + 1

    lines = [
        "---",
        "title: Wiki status",
        "---",
        "",
        "# Wiki status",
        "",
        "Generated by `uv run report` - **do not hand-edit**. It "
        "records how much of the mirrored corpus has been read by the "
        "extraction stage, and when each wiki page was last written.",
        "",
        f"Report generated {date.today().isoformat()}.",
        "",
        "## Extraction coverage",
        "",
        f"{done} of {total} corpus chunks extracted "
        f"({(100 * done / total) if total else 0:.0f}%), across "
        f"{len(plans)} mirrored documents. Only notes that pass the extract "
        f"schema count as extracted"
        + (f"; {invalid} cached note(s) do not, and are queued for "
           f"re-extraction." if invalid else "."),
        "",
        "Chunks by Self Assessment relevance, as judged at extraction:",
        "",
        "| Relevance | Chunks |",
        "|---|---|",
    ]
    for key in ("core", "related", "none", "unknown", "invalid"):
        if relevance.get(key):
            lines.append(f"| {key} | {relevance[key]} |")
    lines += [
        "",
        "| Document | Chunks | Extracted |",
        "|---|---|---|",
    ]
    for p in plans:
        lines.append(f"| `corpus/{p.doc}` | {len(p.chunks)} | {len(p.chunks) - len(p.todo)} |")

    gaps = reconcile.audit(pipeline_fetch.load_sources()).failed
    lines += ["", "## Corpus integrity", ""]
    if gaps:
        lines += [f"{len(gaps)} source(s) are registered as fetched but have no "
                  f"artifact in `corpus/`, so the coverage figures above cover "
                  f"less than the registry claims:", ""]
        lines += [f"- `{g['unit']}`: {g['error']}" for g in gaps]
    else:
        lines.append("Every source registered as fetched has the artifact it "
                     "is configured to write.")

    lines += ["", "## Pages", "", "| Page | Notes used | Written | By |", "|---|---|---|---|"]
    for spec in specs:
        record = manifest.get(spec["id"])
        if record:
            rel = spec["output"].removeprefix("docs/").removesuffix(".md")
            page = f"[{spec['title']}](../{rel}.md)"
            lines.append(f"| {page} | {record.get('note_count', '-')} | "
                         f"{record.get('generated_on', '-')} | `{record.get('generated_by', '-')}` |")
        else:
            lines.append(f"| {spec['title']} | - | not yet generated | - |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render())
    print(f"wrote {OUTPUT.relative_to(OUTPUT.parents[2])}")
    for path in nav.write():
        print(f"wrote {path.relative_to(OUTPUT.parents[2])}")


if __name__ == "__main__":
    main()
